apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: mbakker2000
    provider: github
    repository: http-node-test
  name: mbakker2000-http-node-test
spec:
  description: Imported application for mbakker2000/http-node-test
  httpCloneURL: https://github.com/mbakker2000/http-node-test.git
  org: mbakker2000
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: http-node-test
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/mbakker2000/http-node-test.git
